version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: ark_dino_manager
    ports:
      - 5433:5432
